version: "2"
services:
  client:
    image: node
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./userlist:/userlist
      - /userlist/node_modules
    links:
      - server
    networks:
      - appnetwork
  server:
    image: node
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongodb
    networks:
      - appnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
      - appnetwork
networks:
  appnetwork:
    driver: bridge
